@echo off
chcp 65001 >nul
echo Proverka i ustanovka zavisimostej...
py -m pip install -r requirements.txt
echo Sozdanie papki dlya bazy dannyh...
if not exist "data" mkdir data
echo Zapusk prilozheniya...
python main.py
pause